document_processing:
  chunk_size: 1000
  chunk_overlap: 200

embedding:
  model_id: "amazon.titan-embed-text-v1"

question_generation:
  model_id: "anthropic.claude-3-sonnet-20240229-v1:0"
  max_tokens: 500
  temperature: 0.7

storage:
  vector_store_path: "data/vector_store"

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
